export const apiKey = import.meta.env.VITE_API_KEY;
export const authDomain = import.meta.env.VITE_AUTH_DOMAIN;
export const projectId = import.meta.env.VITE_PROJECT_ID;
export const storageBucket = import.meta.env.VITE_STORAGE_BUCKET;
export const messagingSenderId = import.meta.env.VITE_MESSAGING_SENDER_ID;
export const appId = import.meta.env.VITE_APP_ID;
export const measurementId = import.meta.env.VITE_MEASUREMENT_ID;
export const bienvenida = "Hola!, bienvenido a nuestro sitio!!! ↓ ↓ Todos los Productos";
export const categoria = "↓ ↓ Productos en la Categoría ";
